---
apiVersion: milbi/v2
kind: repo
metadata:
  name: my-backup-repo
  hostalias: "test0r"
spec:
  passphrase: "iamarandompasswort"
  generations: 7
  directory: "~/backups-restic/"
  excludes:
    - "*github.com*"
  content:
    - ~/repos
    - ~/Documents
    - ~/.ssh
