# https://taskfile.dev

version: '3'

env:
  GIT_COMMIT:
    sh: git describe --always --long --dirty
  PROJECT_NAME:
    sh: basename "$PWD"
  WORKDIR: "./milbi"
  PROJECT: la3mmchen
  EXECUTABLE: bin/milbi
  BINARY_NAME: milbi

tasks:
  default:
    cmds:
      - task -l
    silent: true

  fmt:
    dir: "{{.WORKDIR}}"
    desc: "lint code"
    cmds:
      - go mod vendor
      - go fmt

  develop:
    dir: "{{.WORKDIR}}"
    desc: "build-test"
    cmds:
      - task "build"
      - task "test"

  build:
    dir: "{{.WORKDIR}}"
    desc: "build"
    preconditions:
      - task "fmt"
    cmds:
      - task "build:prepare"
      - task "build:executable"
      - task "test:binary"

  test:
    dir: "{{.WORKDIR}}"
    desc: "tests"
    preconditions:
      - task "build"
    cmds:
      - task "test:binary"
      - task "test:gotest:unittests"
      - task "test:gotest:clitests"


  build:prepare:
    dir: "{{.WORKDIR}}"
    desc: "prepare build"
    cmds:
      - go mod tidy
      - go mod vendor
      - go mod verify

  build:executable:
    dir: "{{.WORKDIR}}"
    desc: "build binary"
    cmds:
      - rm -f ${EXECUTABLE}
      - go build -o $EXECUTABLE -ldflags "-X main.AppVersion=$GIT_COMMIT" .

  test:binary:
    dir: "{{.WORKDIR}}"
    desc: "execute the created binary"
    cmds:
      - ./bin/milbi

  test:gotest:unittests:
    dir: "{{.WORKDIR}}"
    desc: "execute gotest"
    cmds:
      - go test -cover -failfast "./.../app"
      - go test -cover -failfast "./.../restic"

  test:gotest:clitests:
    dir: "{{.WORKDIR}}"
    desc: "execute gotest"
    cmds:
      - go test -v -failfast "."
